### PR TITLE
Fixes to Ender library getting stuck.

### LINKED ISSUE #1154: Ender Library getting backed up, unable to extract
Minecraft Version: 1.12.2

Forge Version: 8.0.99.99

Mod Version: 1.19.8

Single Player or Server: Single Player

Describe problem (what you were doing; what happened; what should have happened): So I setup a little automated fishing farm and decided I would filter all of the books I got through an Ender Library to make a nice clean storage area for them. This worked really great by piping everything through the Ender Library, fish and all, and then extracting from the other side again, giving me plain books and all of the other stuff without issue.

That is, until I got 32 of one enchantment and another copy of that enchant came through on a book. That enchanted book simply got stuck. I could no longer extract it via any means. My only option, it seemed, was to break the library block. This gave me the enchanted book back. I could then re place the library and everything continued until the same thing happened again with that enchant or another one that had gotten filled up.

So there's two things that I think are odd here. First, there were about 15 completely empty Ender Bookshelves attached to the library, but the enchant didn't 'overflow' the primary slot into a secondary slot as I thought it should. This would have at least let the system run a bit longer until the entire structure was legitimately full.

The other is that I couldn't get that enchanted book out without breaking the block. I imagine this is to prevent accidentally pulling it out before all of the enchants have been removed under normal working conditions, but there ought to be some way around it other than breaking the block. Like the library could simply release the book after a short amount of time, or if a redstone signal is applied or something. Or the enchantment stripping could be made instant (if it's not already) so that a pipe trying to extract would never have a chance to grab it before it's been treated. 

Log file link: https://gist.github.com/MuteTiefling/e5ab801ca9fba688d0fb38b8769a4e2d

Video/images/gifs (direct upload or link): 

https://imgur.com/a/9o0Chyw

First image is of a test setup I built (I had already torn down the real one) where there's only 1 shelf, so only room for 4 enchants. A fifth enchant is stuck in the shelf. You can see it in the second shot where I've got a tinker's crafting table next to the library to see it's inventory. I cannot manually pull the book from here either.

I tried hoppers and various modded item pipes (including Cyclic's) to no avail.

### PR DESCRIPTION
**Pull request by brad18**
Books with no target no longer get stuck, sent to output slot instead. Fixes #1154

* Books now overflow to a second drawer if first is full. Fixes #1154

* Books with multiple enchantments where the first found enchantment has no target location are correctly handled.

* Changes allow multiple ender libraries to work in series

### CODE REVIEW

File: src/main/java/com/lothrazar/cyclicmagic/block/enchantlibrary/shelf/TileEntityLibrary.java [hunk 1]
```diff
@@ -181,10 +181,13 @@ public QuadrantEnum findEmptyQuadrant() {
     return null;
   }
 
-  public QuadrantEnum findMatchingQuadrant(ItemStack enchBookStack) {
+  public QuadrantEnum findMatchingQuadrant(ItemStack enchBookStack, TileEntityLibrary lib) {
     for (int i = 0; i < storage.length; i++) {
       if (storage[i].doesMatchNonEmpty(enchBookStack)) {
-        return QuadrantEnum.values()[i];
+        QuadrantEnum quad = QuadrantEnum.values()[i];
+        if (lib.getEnchantStack(quad).getCount() < TileEntityLibrary.MAX_COUNT) {
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclicmagic/block/enchantlibrary/shelf/TileEntityLibrary.java]: Looks perfect

File: src/main/java/com/lothrazar/cyclicmagic/block/enchantlibrary/ctrl/TileEntityLibraryCtrl.java [hunk 2]
```diff
@@ -61,22 +62,22 @@ public void update() {
...
       this.setInventorySlotContents(SLOT_OUT, stackIn);
       this.setInventorySlotContents(SLOT_IN, ItemStack.EMPTY);
       return;
     }
-    //try to apply its action to nearby book hey
+    //try to apply its action to nearby book
     EnchantStorageTarget target = BlockLibraryController.findMatchingTarget(world, pos, stackIn);
-    if (target.isEmpty() == false) {
-      //ModCyclic.logger.error(target.library.getPos() + " ? " + target.quad);
+    if (!target.isEmpty()) {
```
Comment (Lothrazar) [inline src/main/java/com/lothrazar/cyclicmagic/block/enchantlibrary/ctrl/TileEntityLibraryCtrl.java]: Not sure why this change is needed, but its just subjective
